"""Classical causal correction baselines for R5."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

import numpy as np
from scipy.integrate import solve_ivp

from .grid import AllenCahnGrid
from .solver import allen_cahn_rhs


@dataclass(frozen=True)
class CausalNudging:
    """Constant-gain local-average correction.

    This baseline uses only the current estimate and current measurement. The
    true state is used by the simulation harness only to generate observations.
    """

    grid: AllenCahnGrid
    nu: float
    observation_matrix: np.ndarray
    gain: float

    def __post_init__(self) -> None:
        matrix = np.asarray(self.observation_matrix, dtype=float)
        if matrix.ndim != 2 or matrix.shape[1] != self.grid.n or matrix.shape[0] == 0:
            raise ValueError("observation_matrix must have shape (q, n)")
        if not np.all(np.isfinite(matrix)):
            raise ValueError("observation_matrix must be finite")
        if not np.isfinite(self.gain) or self.gain < 0.0:
            raise ValueError("gain must be a non-negative finite scalar")
        object.__setattr__(self, "observation_matrix", matrix)

    def rhs(self, estimate: np.ndarray, measurement: np.ndarray) -> np.ndarray:
        state = np.asarray(estimate, dtype=float)
        observed = np.asarray(measurement, dtype=float)
        matrix = self.observation_matrix
        if state.shape != (self.grid.n,):
            raise ValueError(
                f"expected estimate shape {(self.grid.n,)}, got {state.shape}"
            )
        if observed.shape != (matrix.shape[0],):
            raise ValueError(
                f"expected measurement shape {(matrix.shape[0],)}, got {observed.shape}"
            )
        innovation = observed - matrix @ state
        return (
            allen_cahn_rhs(self.grid, self.nu, state)
            + self.gain * (matrix.T @ innovation) / self.grid.h
        )


@dataclass(frozen=True)
class CausalOutputInjection:
    """Causal observer with a general fixed output-injection operator ``B``."""

    grid: AllenCahnGrid
    nu: float
    observation_matrix: np.ndarray
    injection_matrix: np.ndarray

    def __post_init__(self) -> None:
        observation = np.asarray(self.observation_matrix, dtype=float)
        injection = np.asarray(self.injection_matrix, dtype=float)
        if (
            observation.ndim != 2
            or observation.shape[0] == 0
            or observation.shape[1] != self.grid.n
        ):
            raise ValueError("observation_matrix must have shape (q, n)")
        if injection.shape != (self.grid.n, observation.shape[0]):
            raise ValueError("injection_matrix must have shape (n, q)")
        if not np.all(np.isfinite(observation)) or not np.all(np.isfinite(injection)):
            raise ValueError("observer matrices must be finite")
        if not np.isfinite(self.nu) or self.nu <= 0.0:
            raise ValueError("nu must be a positive finite scalar")
        object.__setattr__(self, "observation_matrix", observation)
        object.__setattr__(self, "injection_matrix", injection)

    def rhs(self, estimate: np.ndarray, measurement: np.ndarray) -> np.ndarray:
        state = np.asarray(estimate, dtype=float)
        observed = np.asarray(measurement, dtype=float)
        observation = self.observation_matrix
        if state.shape != (self.grid.n,):
            raise ValueError(
                f"expected estimate shape {(self.grid.n,)}, got {state.shape}"
            )
        if observed.shape != (observation.shape[0],):
            raise ValueError(
                f"expected measurement shape {(observation.shape[0],)}, got {observed.shape}"
            )
        innovation = observed - observation @ state
        return (
            allen_cahn_rhs(self.grid, self.nu, state)
            + self.injection_matrix @ innovation
        )


Observer = CausalNudging | CausalOutputInjection


@dataclass(frozen=True)
class ObserverRollout:
    """Offline truth/estimate trajectory generated by the causal harness."""

    times: np.ndarray
    truth: np.ndarray
    estimate: np.ndarray
    measurements: np.ndarray
    solver_status: int
    solver_message: str

    @property
    def error(self) -> np.ndarray:
        return self.estimate - self.truth

    @property
    def error_mass_norm(self) -> np.ndarray:
        mass_step = 1.0 / (self.error.shape[1] + 1)
        return np.sqrt(np.sum(self.error**2, axis=1) * mass_step)


def simulate_causal_nudging(
    observer: Observer,
    truth_initial: np.ndarray,
    estimate_initial: np.ndarray,
    *,
    t_span: tuple[float, float] = (0.0, 1.0),
    output_times: np.ndarray | None = None,
    noise: Callable[[float], np.ndarray] | None = None,
    rtol: float = 1e-9,
    atol: float = 1e-11,
) -> ObserverRollout:
    """Simulate a causal observer using an offline-generated measurement stream."""

    n = observer.grid.n
    truth = np.asarray(truth_initial, dtype=float)
    estimate = np.asarray(estimate_initial, dtype=float)
    if truth.shape != (n,) or estimate.shape != (n,):
        raise ValueError(f"truth_initial and estimate_initial must have shape {(n,)}")
    times = (
        np.asarray(output_times, dtype=float)
        if output_times is not None
        else np.linspace(t_span[0], t_span[1], 101)
    )
    if times.ndim != 1 or times.size == 0 or np.any(np.diff(times) < 0.0):
        raise ValueError(
            "output_times must be a sorted, non-empty one-dimensional array"
        )

    result = solve_ivp(
        lambda time, state: observer_rhs_with_truth(
            time,
            state,
            observer=observer,
            noise=noise,
        ),
        t_span,
        np.concatenate((truth, estimate)),
        method="DOP853",
        t_eval=times,
        rtol=rtol,
        atol=atol,
    )
    if result.y.shape != (2 * n, times.size):
        raise RuntimeError("observer rollout returned an incomplete trajectory")
    trajectories = result.y.T
    truth_trajectory = trajectories[:, :n]
    estimate_trajectory = trajectories[:, n:]
    measurements = np.asarray(
        [observer.observation_matrix @ value for value in truth_trajectory],
        dtype=float,
    )
    if noise is not None:
        measurements += np.asarray([noise(float(time)) for time in times], dtype=float)
    return ObserverRollout(
        times=times,
        truth=truth_trajectory,
        estimate=estimate_trajectory,
        measurements=measurements,
        solver_status=int(result.status),
        solver_message=str(result.message),
    )


def observer_rhs_with_truth(
    time: float,
    combined_state: np.ndarray,
    *,
    observer: Observer,
    noise: Callable[[float], np.ndarray] | None = None,
) -> np.ndarray:
    """RHS for a truth/estimate pair, used only by the offline test harness."""

    n = observer.grid.n
    combined = np.asarray(combined_state, dtype=float)
    if combined.shape != (2 * n,):
        raise ValueError(
            f"expected combined state shape {(2 * n,)}, got {combined.shape}"
        )
    truth, estimate = combined[:n], combined[n:]
    measurement = observer.observation_matrix @ truth
    if noise is not None:
        perturbation = np.asarray(noise(float(time)), dtype=float)
        if perturbation.shape != measurement.shape:
            raise ValueError("noise function returned the wrong shape")
        measurement = measurement + perturbation
    return np.concatenate(
        (
            allen_cahn_rhs(observer.grid, observer.nu, truth),
            observer.rhs(estimate, measurement),
        )
    )
